apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.backend.port }}
  selector:
    app: backend