apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.port }}
  selector:
    app: frontend