apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app-chart.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /backend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "app-chart.fullname" . }}-backend
            port:
              number: 80
      - path: /frontend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "app-chart.fullname" . }}-frontend
            port:
              number: 80