clusterName: ${cluster_name}
region: ${region}
vpcId: ${vpc_id}

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  name: aws-load-balancer-controller-terraform

nodeSelector:
  workload: tools  